#!/bin/bash
#SBATCH --job-name=uni_sim_Nbody
#SBATCH --partition=shortq
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --time=24:00:00
#SBATCH --cpus-per-task=16
export OMP_NUM_THREADS=${SLURM_CPUS_PER_TASK}

#For jobs supporting OpenMP, assign the value of the requested CPU cores to the OMP_NUM_THREADS variable
#that would be automatically passed to your command supporting OpenMP


cd /gpfs-scratch/m220590ph/FrontEnd_cosmo
bash main_nbody.sh
echo “Job finished successfully”

